import SwiftUI

struct TermsView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                Text("Terms & Conditions")
                    .font(.largeTitle)
                    .fontWeight(.bold)
                
                Text("Last Updated: February 2026")
                    .font(.caption)
                    .foregroundColor(.secondary)
                
                SectionView(title: "Usage Policy", content: """
                Is This Vegan? is provided for personal, non-commercial use. To ensure the service remains available to everyone, we may limit the number of scans per user if excessive usage is detected ("Reasonable Use Policy").
                """)
                
                SectionView(title: "AI Disclaimer", content: """
                The analysis provided by this app is generated by Artificial Intelligence (Google Gemini). While we strive for accuracy, AI can make mistakes.
                
                The results should be used as a guide only and not as absolute fact. Always double-check the physical ingredient list on the product packaging, especially if you have severe allergies.
                """)
                
                SectionView(title: "Not Medical Advice", content: """
                This application does not provide medical or nutritional advice. If you have specific dietary requirements or allergies, please consult with a healthcare professional.
                """)
                
                SectionView(title: "Liability", content: """
                The developers of Is This Vegan? are not liable for any errors, omissions, or misinterpretations of the ingredient data. Use of this app is at your own risk.
                """)
                
                Spacer()
            }
            .padding()
        }
        .navigationTitle("Terms & Conditions")
        .navigationBarTitleDisplayMode(.inline)
    }
}

#Preview {
    NavigationView {
        TermsView()
    }
}
